import type { Metadata, Viewport } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans, Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Dock } from "@/components/shell/Dock";
import { PathBar } from "@/components/shell/PathBar";
import "./globals.css";

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plex-mono",
  display: "swap",
});

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-plex-sans",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

// Placeholder from the scaffold; replaced in step 12.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#edf0f3" },
    { media: "(prefers-color-scheme: dark)", color: "#0d1117" },
  ],
  // Lets the dock pad itself above the home indicator on phones.
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${plexMono.variable} ${plexSans.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="ahsan-theme"
          disableTransitionOnChange
        >
          {/* Shell (PLAN.md §3): path bar, scrolling screen area, dock. Page padding 20px
              (12px on phones), 12px gaps (10px on phones). */}
          <div className="flex h-dvh flex-col gap-2.5 p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))] sm:gap-3 sm:p-5 sm:pb-5">
            <PathBar />
            <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain">{children}</main>
            <Dock />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
